[package]
name = "ms-mdm"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
easy-xml = "0.1.4"
easy-xml-derive = "0.1.4"
xml = "0.8.20"

[dev-dependencies]
pretty_assertions = "1.4.1"
